---
- include_tasks: setup-Ubuntu.yml
  when: ansible_os_family == 'Debian'

- name: Install .NET SDK
  package:
    name: "{{ dotnet_sdk_package }}"
    state: present
  become: true

- name: Aliasing dotnet to dn
  lineinfile:
    dest: "~/.bash_aliases"
    regexp: '^alias dn='
    line: 'alias dn=dotnet'