---
- name: Ensure dependencies are installed
  apt:
    name:
      - apt-transport-https
    state: present
  become: true

- name: Add NodeSource apt key
  apt_key:
    url: "{{ nodejs_apt_gpg_key }}"
    state: present
  become: true

- name: Add NodeSource repository
  apt_repository:
    repo: "{{ nodejs_apt_repository }}"
    state: present
    update_cache: true
  become: true